"""
Django settings for service_account project.

Generated by 'django-admin startproject' using Django 1.11.14.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
from module.path import KEYS_PATH, DUMP_JOB_PATH 

import sys
sys.path.append(KEYS_PATH)


import nsg_key, pizdaint_key, database_key, production_key 

UMBRELLA = True

if UMBRELLA:
    NSG_APPKEY = nsg_key.UMBRELLA_APPKEY
    NSG_USER = nsg_key.UMBRELLA_USER
    NSG_PASSWORD = nsg_key.UMBRELLA_PASSWORD
else:
    NSG_APPKEY = nsg_key.APPKEY
    NSG_USER = nsg_key.USER
    NSG_PASSWORD = nsg_key.PASSWORD

PIZDAINT_USER = pizdaint_key.USER
PIZDAINT_PASSWORD = pizdaint_key.PASSWORD


import os

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'default': {
#             'format': '<%(asctime)-12s %(name)s> [%(levelname)s]: \t %(message)s',
#         },
#     },
#     'handlers': {
#         'debug': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'formatter': 'default',
#             'filename': '/var/log/service_account.log',
#         },
#         # 'mail_admins': {
#         #     'level': 'ERROR',
#         #     'class': 'django.utils.log.AdminEmailHandler',
#         #     'filters': ['special'],
#         # },
#     },
#     'loggers': {
#         '': {
#             'handlers': ['debug'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
#
# }


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_DIR = os.path.dirname(os.path.join(BASE_DIR, 'media'))

HBP_MY_USER_URL = 'https://services.humanbrainproject.eu/idm/v1/api/user/me'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret keys used in production secret!
SECRET_KEY = production_key.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False 

# NETWORK SETTINGS: set your ip/domain here.
ALLOWED_HOSTS = [
    '*',
]

CORS_ORIGIN_ALLOW_ALL = True

#CORS_ALLOW_HEADERS = [
#    'token',
#    'authorization',
#    'content-type',
#    'user-agent',
#    'x-csrftoken',
#    'x-requested-with',
#]


CORS_ORIGIN_WHITELIST = [
    #'https://2.237.33.252:14786/' + '*',
    #'https://collab.humanbrainproject.eu/' + '*',
]

# HPC SETTINGS: add/enable your hpc here. This field is directly linked to 'project.hpc' on 'avm/models.py'.
ENABLED_HPC = [
    ('NSG', 'NeuronScienceGateway'),
    ('PIZDAINT', 'PizDaint-CSCS')
]

# PROJECT SETTINGS: add here witch project is enabled by default, one project per HPC
DEFAULT_PROJECT = {
    'NSG': 'bsp_nsg_01',
    'PIZDAINT': 'bsp_pizdaint_01'
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'service_account',
    'avm',
    'nsg',
    'pizdaint',
    'hbp_app_python_auth',
    'sslserver',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'service_account.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'service_account.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': database_key.NAME,
        'USER': database_key.USER,
        'PASSWORD': database_key.PASSWORD,
        'HOST': database_key.HOST,
        'PORT': database_key.PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


REST_FRAMEWORK = {
    'DEAFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
}
