"""
Constants.
"""

DEVELOPMENT = 'development'
PRODUCTION = 'production'

USER_TIME_SETTING_NAME = 'User time'
USER_TIME_SETTING_VALUE = '18000000' # 5h

USER_SPACE_SETTING_NAME = 'User space'
USER_SPACE_SETTING_VALUE = '10000000' # 10GB

PROJECT_TIME_SETTING_NAME = 'Project time'
PROJECT_TIME_SETTING_VALUE = '1800000' # 0.5h

PROJECT_SPACE_SETTING_NAME = 'Project space'
PROJECT_SPACE_SETTING_VALUE = '1000000' # 1GB

HPC_BACKEND_SETTING_NAME = 'HPC backend type'
HPC_BACKEND_SETTING_VALUE = ['Unicore', 'NSG']
