# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-28 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host_institution', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=50)),
                ('cpus', models.IntegerField()),
                ('gpus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100)),
                ('init_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('runtime', models.FloatField()),
                ('stage', models.CharField(max_length=20)),
                ('terminal_stage', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hpc', models.CharField(choices=[(b'NSG', b'NeuronScienceGateway'), (b'PIZDAINT', b'PizDaint-CSCS')], max_length=20)),
                ('init_time', models.IntegerField()),
                ('init_space', models.FloatField()),
                ('time_left', models.IntegerField(null=True)),
                ('space_left', models.FloatField(null=True)),
                ('user_time', models.IntegerField(default=18000000)),
                ('user_space', models.FloatField(default=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left', models.IntegerField(blank=True, null=True)),
                ('space_left', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avm.Project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('banned_from', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='quota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avm.User'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'hpc')]),
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avm.User'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avm.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='quota',
            unique_together=set([('user', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('job_id', 'project')]),
        ),
	migrations.RunSQL(
	    "insert into avm_project values ('1', 'bsp_nsg_01', 'NSG', '10000000', '10000000.0', '10000000', '10000000.0', '18000000', '10000000.0')"
        ),
        migrations.RunSQL(
            "insert into avm_project values ('2', 'bsp_pizdaint_01', 'PIZDAINT', '10000000', '10000000.0', '10000000', '10000000.0', '18000000', '10000000.0')"
        ),
    ]
