# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-14 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banned_from',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.CharField(default='', max_length=100),
        ),
    ]
