# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avm', '0002_auto_20190314_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
