# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-21 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avm', '0003_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
