# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-11-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avm', '0004_auto_20190321_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
