# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-02-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avm', '0006_advancedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='init_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='stage',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
