# Generated by Django 3.0.2 on 2020-03-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avm', '0008_auto_20200221_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hpc',
            field=models.CharField(choices=[('NSG', 'NeuronScienceGateway'), ('PIZDAINT', 'PizDaint-CSCS')], max_length=20),
        ),
    ]
